name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build packages
        run: pnpm run build --filter=@depinautopilot/core --filter=@depinautopilot/utils
        continue-on-error: true

      - name: Run tests
        run: |
          cd packages/core
          npm test -- --run
        continue-on-error: true

      - name: Type check
        run: pnpm run type-check
        continue-on-error: true

      - name: Lint check
        run: pnpm run lint
        continue-on-error: true
